Added Subconscious
ucan-wg/ucan-check pull request #37
Opened 2022-05-22 01:30 UTC by bmann

Adding Subconscious to the community page. Where we should also link Fission, among other things :)

@cdata @gordonbrander just added links to your stuff on the community page -- feel free to edit / suggest changes

2022-05-22 02:06 UTC, gordonbrander commented
Love it! (Note to self, it's time to build a proper website for Subconscious)

2022-05-23 15:53 UTC, bgins requested changes
Excellent, great to get links for Subconscious the Rust UCAN implementation in here! 🎉 

One small change request -- could we add an empty line after the list item? Without the empty line, there is a preprocessing error which is probably from the markdown parser.

2022-05-23 15:54 UTC, bgins commented on src/routes/community.md
> +* <OutboundLink  href="https://subconscious.substack.com/">Subconscious</OutboundLink> is a distributed note taking tool that <OutboundLink href="https://subconscious.substack.com/p/layered-protocols
Add an extra line below this to separate out the `</div>`.

2022-05-25 15:58 UTC, bgins approved these changes
Looks good! 🎉

2022-05-25 15:59 UTC, merged